"""profile handle

Revision ID: 759c408ee946
Revises: e3f418d7d08f
Create Date: 2018-08-24 22:42:26.519391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759c408ee946'
down_revision = 'e3f418d7d08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('twitterhandle', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'twitterhandle')
    # ### end Alembic commands ###
