"""profile fullanme

Revision ID: c9fb5c29571e
Revises: 759c408ee946
Create Date: 2018-08-25 03:07:36.855604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fb5c29571e'
down_revision = '759c408ee946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('fullname', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'fullname')
    # ### end Alembic commands ###
