"""proj scantasks

Revision ID: e3fa069fed69
Revises: c9fb5c29571e
Create Date: 2018-08-26 05:57:04.434934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fa069fed69'
down_revision = 'c9fb5c29571e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('scantasks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'scantasks')
    # ### end Alembic commands ###
